// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvTUI4Bs4dIZtpebUjsyqiZ0tnjHyMY8',
    appId: '1:486754750542:web:a6337f0b5bb870d997f31f',
    messagingSenderId: '486754750542',
    projectId: 'mini-social-media-applic-99f9b',
    authDomain: 'mini-social-media-applic-99f9b.firebaseapp.com',
    storageBucket: 'mini-social-media-applic-99f9b.firebasestorage.app',
    measurementId: 'G-33XXZKG82S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOA_qIYcUzOo_FSZ7lXRLPFZ-uFCWwWs',
    appId: '1:486754750542:android:611d3d515783050097f31f',
    messagingSenderId: '486754750542',
    projectId: 'mini-social-media-applic-99f9b',
    storageBucket: 'mini-social-media-applic-99f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC988SkPGNm13mxBDGWwtkNvI1-rykHVQk',
    appId: '1:486754750542:ios:953dae984e34aa8697f31f',
    messagingSenderId: '486754750542',
    projectId: 'mini-social-media-applic-99f9b',
    storageBucket: 'mini-social-media-applic-99f9b.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC988SkPGNm13mxBDGWwtkNvI1-rykHVQk',
    appId: '1:486754750542:ios:953dae984e34aa8697f31f',
    messagingSenderId: '486754750542',
    projectId: 'mini-social-media-applic-99f9b',
    storageBucket: 'mini-social-media-applic-99f9b.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialMediaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvTUI4Bs4dIZtpebUjsyqiZ0tnjHyMY8',
    appId: '1:486754750542:web:f1718b1f01bf18a597f31f',
    messagingSenderId: '486754750542',
    projectId: 'mini-social-media-applic-99f9b',
    authDomain: 'mini-social-media-applic-99f9b.firebaseapp.com',
    storageBucket: 'mini-social-media-applic-99f9b.firebasestorage.app',
    measurementId: 'G-1H3T6429YL',
  );
}
